# https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2yaml

# additional configuration to the config in the root of the project
# this additional config is used during the markdownlint CI job

# use custom rule contained in supplementary rules image as a workaround
# more details: https://github.com/DavidAnson/vscode-markdownlint/issues/336
customRules:
  # Enforce one sentence per line
  # semantic line breaks (https://sembr.org/)
  # See: https://github.com/DavidAnson/markdownlint/pull/719
  - "markdownlint-rule-max-one-sentence-per-line"

outputFormatters:
  - - markdownlint-cli2-formatter-template
    # https://github.com/DavidAnson/markdownlint-cli2/blob/50e1be2d6f205fdc2f2aca1f786c882e9fce5aac/formatter-template/README.md#examples
    - template: "::error file=${fileName},line=${lineNumber},${columnNumber:col=${columnNumber},}title=${ruleName}::${ruleDescription} [Context:\"${errorContext}\"]"
  - - markdownlint-cli2-formatter-pretty
